Repository Gregam3/ASEGroup1, pull requests merged in 2018-12, with the labels that each got.

#212 Gm 203m3 fix tests
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryData.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/main/java/asegroup1/api/services/landregistry/MathUtil.java
  backend/src/test/java/asegroup1/api/controllers/LandRegistryControllerTest.java
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: bug

#222 Jf 221 clean up land registry service impl
  .clang-format
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: Code Quality, bug

#231 Fix for travis not automatically deploying master branch
  .travis.yml
Labels: bug

#238 Colour generation improvements
  backend/src/main/java/asegroup1/api/models/heatmap/Colour.java
  backend/src/test/java/asegroup1/api/models/heatmap/ColourTest.java
  backend/src/test/java/asegroup1/api/models/landregistry/heatmap/ColourTest.java
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: enhancement

#244 Gm 236m1 test coverage
  backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java
  backend/src/main/java/asegroup1/api/models/heatmap/Colour.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/java/asegroup1/api/models/heatmap/ColourTest.java
  backend/src/test/java/asegroup1/api/models/heatmap/HeatMapDataPointTest.java
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: enhancement
