Repository Gregam3/ASEGroup1, pull requests merged in 2018-10, with the labels that each got.

#3 Gm 2 react native map application
  .babelrc
  .gitignore
  .watchmanconfig
  App.js
  app.json
  assets/icon.png
  assets/splash.png
  package.json
Labels: good first issue

#13 QA Review for 2.0
  React/.babelrc
  React/.gitignore
  React/.watchmanconfig
  React/App.js
  React/app.json
  React/assets/icon.png
  React/assets/splash.png
  React/package.json
  React/readme.txt
Labels: enhancement

#38 Jf 33 maven cli build issue
  backend/.gitignore
  backend/README.md
  backend/locationReciever.iml
  backend/pom.xml
  backend/src/main/java/asegroup1/api/Application.java
  backend/src/main/java/asegroup1/api/controllers/GeolocationController.java
  pom.xml
Labels: bug

#61 Be 20 m0 app modification to send location
  backend/src/test/asegroup1/api/services/user/UserServiceImplTest.java
  frontend/reactnative/App.js
  frontend/reactnative/lib/NetworkingLib.js
  frontend/reactnative/package.json
Labels: enhancement

#69 Working react client
  frontend/reactnative/App.js
  frontend/reactnative/lib/Auth.js
  frontend/reactnative/lib/NetworkingLib.js
Labels: enhancement

#70 Release 3.0
  backend/.gitignore
  backend/README.md
  backend/pom.xml
  backend/src/main/java/asegroup1/api/Application.java
  backend/src/main/java/asegroup1/api/configs/SwaggerConfig.java
  backend/src/main/java/asegroup1/api/controllers/LocationController.java
  backend/src/main/java/asegroup1/api/controllers/UserController.java
  backend/src/main/java/asegroup1/api/daos/Dao.java
  backend/src/main/java/asegroup1/api/daos/DaoImpl.java
  backend/src/main/java/asegroup1/api/daos/location/LocationDaoImpl.java
  backend/src/main/java/asegroup1/api/daos/user/UserDaoImpl.java
  backend/src/main/java/asegroup1/api/models/LocationData.java
  backend/src/main/java/asegroup1/api/models/UserData.java
  backend/src/main/java/asegroup1/api/services/ServiceImpl.java
  backend/src/main/java/asegroup1/api/services/location/LocationServiceImpl.java
  backend/src/main/java/asegroup1/api/services/user/UserServiceImpl.java
  backend/src/main/resources/application.properties
  backend/src/test/asegroup1/api/services/user/UserServiceImplTest.java
  database/createscripts/CreateTables.sql
  frontend/reactnative/.babelrc
  frontend/reactnative/.gitignore
  frontend/reactnative/.watchmanconfig
  frontend/reactnative/App.js
  frontend/reactnative/app.json
  frontend/reactnative/assets/icon.png
  frontend/reactnative/assets/splash.png
  frontend/reactnative/lib/Auth.js
  frontend/reactnative/lib/Config.js
  frontend/reactnative/lib/NetworkingLib.js
  frontend/reactnative/package.json
  frontend/reactnative/readme.txt
Labels: bug, enhancement
