Repository Gregam3/ASEGroup1, pull requests merged in 2018-11, with the labels that each got.

#85 Gm 83 integrate sparql
  backend/pom.xml
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/models/HouseTransactionData.java
  backend/src/main/java/asegroup1/api/models/LandRegistryData.java
  backend/src/main/java/asegroup1/api/models/LandRegistryDataWithTransaction.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/main/java/asegroup1/api/services/landregistry/queries.properties
Labels: enhancement

#89 Created simple unit test for sparql query generator via getLandRegist…
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/models/Address.java
  backend/src/main/java/asegroup1/api/models/AddressWithTransaction.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
  frontend/reactnative/lib/Auth.js
Labels: enhancement

#105 Gm 98m0 convert addresses to lat and long
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/models/Address.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: enhancement

#90 Made entitymanager thread-safe
  backend/src/main/java/asegroup1/api/daos/DaoImpl.java
Labels: enhancement

#109 Jf 76 build backend to docker image
  backend/Dockerfile
  backend/README.md
Labels: enhancement

#110 Gm 102 location range post code filtering
  backend/pom.xml
  backend/src/main/java/asegroup1/api/daos/DaoImpl.java
  backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java
  backend/src/main/java/asegroup1/api/models/PostCodeCoordinates.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: enhancement

#141 Changed postcode checking to formatting and added formatting tests
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/java/asegroup1/api/controllers/LandRegistryControllerTest.java
Labels: Code Quality

#145 Gm 140m0 paon address name fix
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
Labels: bug

#155 Add dummy data markers to map
  frontend/reactnative/App.js
Labels: enhancement

#161 Added automatic push to docker repository
  .travis.yml
  backend/README.md
Labels: enhancement

#170 Gm 146m2 auto aggregate data
  backend/src/main/java/asegroup1/api/Application.java
  backend/src/main/java/asegroup1/api/configs/SwaggerConfig.java
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/controllers/LocationController.java
  backend/src/main/java/asegroup1/api/controllers/UserController.java
  backend/src/main/java/asegroup1/api/daos/DaoImpl.java
  backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java
  backend/src/main/java/asegroup1/api/daos/location/LocationDaoImpl.java
  backend/src/main/java/asegroup1/api/daos/user/UserDaoImpl.java
  backend/src/main/java/asegroup1/api/models/heatmap/Colour.java
  backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryData.java
  backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryQuery.java
  backend/src/main/java/asegroup1/api/services/ServiceImpl.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  backend/src/main/java/asegroup1/api/services/location/LocationServiceImpl.java
  backend/src/test/java/asegroup1/api/controllers/UserControllerTest.java
  backend/src/test/java/asegroup1/api/models/landregistry/LandRegistryQueryTestUtils.java
  backend/src/test/java/asegroup1/api/models/landregistry/heatmap/ColourTest.java
  backend/src/test/java/asegroup1/api/services/landregistry/LandRegistryServiceImplTest.java
  backend/src/test/java/asegroup1/api/services/user/UserServiceImplTest.java
Labels: enhancement

#157 added circle for heatmap
  frontend/reactnative/App.js
Labels: enhancement

#196 Gm 152 get real marker data
  backend/src/main/java/asegroup1/api/controllers/LandRegistryController.java
  backend/src/main/java/asegroup1/api/controllers/fake-responses.properties
  backend/src/main/java/asegroup1/api/daos/landregistry/LandRegistryDaoImpl.java
  backend/src/main/java/asegroup1/api/models/landregistry/LandRegistryData.java
  backend/src/main/java/asegroup1/api/services/landregistry/LandRegistryServiceImpl.java
  frontend/reactnative/App.js
  frontend/reactnative/lib/NetworkingLib.js
Labels: enhancement

#198 Jf 129 add auto generate swagger docs
  backend/pom.xml
  backend/src/test/java/asegroup1/api/swagger/Swagger2MarkupTest.java
Labels: enhancement

#199 Jf 34 m0 fix pre commit script bug
  .clang-format
Labels: bug, enhancement

#205 Added pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
